name: Labels
on: push

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      # sync labels
      - uses: crazy-max/ghaction-github-labeler@v5
        if: success()
