name: Labels
on: push

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # sync labels
      - uses: crazy-max/ghaction-github-labeler@v5
        if: success()
